Table usuarios {
    id int [pk, increment]
    name varchar(100)
    email varchar(100) [unique]
    password varchar(100)

    estado varchar(50) [default: `activo`]

    creado_en timestamp [default: `now()`]
    actualizado_en timestamp [default: `now()`]
    eliminado_en timestamp [default: `now()`]
}

Table clientes {
    id int [pk, increment]
    user_id int [ref: > usuarios.id]

    nombres varchar(100)
    apellidos varchar(100)
    tipo_documento varchar(50)
    numero_documento varchar(50) [unique]
    celular varchar(20)
    direccion varchar(200)
    fecha_nacimiento date
    genero varchar(20)
    foto_perfil varchar(255)
    contacto_nombre varchar(100)
    contacto_telefono varchar(20)
    contacto_relacion varchar(50)
    
    creando_en timestamp [default: `now()`]
    actualizado_en timestamp [default: `now()`]
    eliminado_en timestamp [default: `now()`]
}

Table categorias {
     id int [pk, increment]
     nombre varchar(100)
     
    creado_en timestamp [default: `now()`]
    actualizado_en timestamp [default: `now()`]
}

Table prestamos {
    id int [pk, increment]

    cliente_id int [ref: > clientes.id]
    categoria_id int [ref: > categorias.id]

    monto_prestado decimal(10,2)
    tasa_interes decimal(5,2)
    modalidad_pago varchar(50)
    modalidad_amortizacion varchar(50)
    nro_cuotas int
    monto_interes_total decimal(10,2)
    monto_total_a_pagar decimal(10,2)
    fecha_inicio date
    estado varchar(50) [default: 'pendiente']

    creado_en timestamp [default: `now()`]
    actualizado_en timestamp [default: `now()`]
}